linters-settings:
  govet:
    enable:
      - shadow
      - tests
  revive:
    confidence: 0.8
    rules:
      - name: line-length-limit
        arguments: [120]
  unused:
    exported-fields-are-used: false
    local-variables-are-used: false 
    generated-is-used: false
  cyclop:
    max-complexity: 7

# Configuration for golangci-lint that is suitable for a Kubernetes operator project built with Golang
linters:
  enable-all: false
  disable-all: false
  enable:
    - goconst
    - gocritic
    - govet
    - revive # Replaces golint
    - unused
    - cyclop
    - copyloopvar  # Replaces scopelint
issues:
  exclude-dirs: 
    - vendor
    - bundle
    - hack
    - img
  exclude-rules:
    - path: _test\.go
      linters:
        - testpackage
run:
  timeout: 5m